frameworkVersion: '1.78.1'
service: nicopalenque-integrador

plugins:
  - serverless-iam-roles-per-function
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev

functions:
  - ${file(src/create-client/index.yml)}
  - ${file(src/create-card/index.yml)}
  - ${file(src/create-gift/index.yml)}
  - ${file(src/list-client/index.yml)}

resources:
  - ${file(resource/create-client/dynamodb.yml)}
  - ${file(resource/create-client/notification.yml)}
  - ${file(resource/create-card/queue.yml)}
  - ${file(resource/create-gift/queue.yml)}