Resources:

  CreateGiftQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-${self:provider.stage}-create-gift-queue
      
  CreateGiftQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      PolicyDocument: 
        Statement:
          - Effect: Allow
            Action: 
              - SQS:*
            Resource: !GetAtt CreateGiftQueue.Arn
            Principal:
              AWS:
                - !Ref AWS::AccountId
          - Effect: Allow
            Principal:
              AWS: 
                - '*'
            Action: 
              - SQS:SendMessage
            Resource: !GetAtt CreateGiftQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn:
                  - !Ref ClientCreatedTopic
      Queues: 
        - !Ref CreateGiftQueue