Resources:

  ClientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${self:provider.stage}-create-client
      AttributeDefinitions:
        - AttributeName: dni
          AttributeType: S
      KeySchema:
        - AttributeName: dni
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1