Resources:
      
  ClientCreatedTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Client Created Topic
      TopicName: ${self:service}-${self:provider.stage}-client-created-topic
      Subscription:
        - Protocol: sqs
          Endpoint: !GetAtt CreateCardQueue.Arn
        - Protocol: sqs
          Endpoint: !GetAtt CreateGiftQueue.Arn